name: Build and Deploy a Jekyll Site to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: pull and setup environment
        uses: actions/checkout@v4
      - name: setup environment
        uses: jdx/mise-action@v3
      - name: build site
        run: jekyll build
      - name: 🚀 deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
